name: my_cool_game
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bonfire: ^3.12.3
  cupertino_icons: ^1.0.8
  flame_audio: ^2.10.2
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  lottie: ^3.2.0
  material_design_icons_flutter: ^7.0.7296
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: adventure
      fonts:
        - asset: fonts/adventure.otf

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/lotties/

    # Alchemist
    - assets/images/alchemist/

    # Background
    - assets/images/background/

    # Blacksmith
    - assets/images/blacksmith/

    # Bonfire
    - assets/images/bonfire/

    # Chest
    - assets/images/chest/

    # Coin
    - assets/images/coin/

    # Dwarf Warrior
    - assets/images/dwarf_warrior/idle/
    - assets/images/dwarf_warrior/walk/
    - assets/images/dwarf_warrior/attack/
    - assets/images/dwarf_warrior/hurt/
    - assets/images/dwarf_warrior/death/

    # Gem
    - assets/images/gem/

    # Headless Horseman
    - assets/images/headless_horseman/idle/
    - assets/images/headless_horseman/run/
    - assets/images/headless_horseman/attack/
    - assets/images/headless_horseman/hurt/
    - assets/images/headless_horseman/death/

    # Input
    - assets/images/input/

    # Item
    - assets/images/item/

    # Lizardman
    - assets/images/lizardman/idle/
    - assets/images/lizardman/walk/
    - assets/images/lizardman/attack/
    - assets/images/lizardman/hurt/
    - assets/images/lizardman/death/

    # Minotaur
    - assets/images/minotaur/idle/
    - assets/images/minotaur/walk/
    - assets/images/minotaur/attack_one/
    - assets/images/minotaur/attack_two/
    - assets/images/minotaur/hurt/
    - assets/images/minotaur/death/

    # Plant
    - assets/images/plant/

    # Potion
    - assets/images/potion/

    # World Object
    - assets/images/world_object/
